apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jupyterhub
  namespace: kube-system
spec:
  chart: jupyterhub
  repo: https://jupyterhub.github.io/helm-chart/
  targetNamespace: default
  valuesContent: |-
    cull:
      users: False
    hub:
      redirectToServer: false
      db:
        type: sqlite-memory
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
       - effect: NoExecute
         key: CriticalAddonsOnly
         operator: "Exists"
    proxy:
      secretToken: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
      service:
        type: ClusterIP
      chp:
        tolerations:
          - effect: NoExecute
            key: CriticalAddonsOnly
            operator: "Exists"
        nodeSelector:
          node-role.kubernetes.io/master: "true"
    ingress:
      enabled: true
    singleuser:
      events: true
      defaultUrl: "/lab"
      storage:
        type: none
      profileList:
      - default: true
        slug: "RA 1"
        description: "Run:AI Profile"
        display_name: "Run:AI with 1 GPU"
        kubespawner_override:
          image: jupyter/datascience-notebook
          tag: 177037d09156
          extra_resource_limits:
            nvidia.com/gpu: "1"


