name: Terraform code quality
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/lint.yaml"
  push:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/lint.yaml"
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
    - name: Terraform fmt
      run: terraform fmt
      continue-on-error: true
  tflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
    - name: Run terraform init
      run: terraform init
    - name: Run TFLint
      run: tflint -f compact
